### ISSUE TITLE
Markdown README is not rendered correctly in PyPI

### ISSUE THREAD

**Issue by elopez** [trailofbits/solc-select#188]
### Describe the issue:

The solc-select README that gets uploaded to PyPI is a markdown document, but due to a misconfiguration it is not rendered correctly in the PyPI site:

![Screenshot 2023-06-26 at 13 32 15](https://github.com/crytic/solc-select/assets/2642849/0c2d7f9d-a2c3-4724-8e79-f47c5546fbaa)

I think this can be solved with adding something like `long_description_content_type="text/markdown",` in setup.py. You can get more information on how the README in PyPI works in this link: https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/

**Comment by AmitT98** [comment]
Hi @elopez ,can you give a little more clarification, as to what you actually want to do?

**Comment by elopez** [comment]
Hi @AmitT98, I expanded a bit on the issue now 👍

**Comment by AmitT98** [comment]
Hi @elopez I would like to work on the issue, can you please assign it to me?

**Comment by AmitT98** [comment]
Hello @elopez I have resolved the issue, I tested it on testpypi and I think it renders properly. Please do check it once.[https://test.pypi.org/project/solc-select/1.0.5/](https://test.pypi.org/project/solc-select/1.0.5/). Let me know if this is good enough, so that I can raise a pull request.

**Comment by AmitT98** [comment]
Hi @elopez . I made the necessary changes and now it renders correctly. I created a pypitest to verify the same. Please check it here. [https://test.pypi.org/project/solc-select/1.0.5/](https://test.pypi.org/project/solc-select/1.0.5/). Let me know if this is good enough, so that I can raise a PR.
Query: I have increased the version to 1.0.5 as this is minor change, should this be kept same?

**Comment by elopez** [comment]
Awesome! Go ahead with a PR 👍 and please keep the version the same, just include the fix on it.
